In [14]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

## Series
“A Series là một đối tượng giống như mảng một chiều chứa một chuỗi giá trị (có kiểu tương tự như kiểu NumPy) và một mảng nhãn dữ liệu được liên kết, được gọi là chỉ mục của nó. Chuỗi đơn giản nhất được hình thành chỉ từ một mảng dữ liệu ”


In [3]:
obj = pd.Series([4,6,-5,3])

In [4]:
obj

0    4
1    6
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  6, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [12]:
obj2 *2 

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
# create series by dict

sdata = {'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}

In [18]:
obj3 = pd.Series(sdata)

In [19]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

“When you are only passing a dict, the index in the resulting Series will have the dict’s keys in sorted order. You can override this by passing the dict keys in the order you want them to appear in the resulting Series:”


In [20]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(sdata,index = states)

In [22]:
obj4 # mising for Nan

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [23]:
pd.isnull(obj4) # check Nan

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4) # check Nan

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
## Series also has thees as instance methods
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

## Data Frame
DataFrame đại diện cho một bảng dữ liệu hình chữ nhật và chứa một tập hợp các cột có thứ tự, mỗi cột có thể là một kiểu giá trị khác nhau (số, chuỗi, boolean, v.v.). DataFrame có cả chỉ mục hàng và cột; nó có thể được coi như một **dict** của **Series** tất cả chia sẻ cùng một chỉ mục. Bên dưới, dữ liệu được lưu trữ dưới dạng một hoặc nhiều khối hai chiều chứ không phải là danh sách, dict hoặc một số tập hợp mảng một chiều khác. Các chi tiết chính xác về nội bộ của DataFrame nằm ngoài phạm vi của cuốn sách này. "

## Create data frame 

In [27]:
data = {
    'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
    'year': [2000,2001,2002,2001,200,2003],
    'pop': [1.5,1.7,3.6,2.4,2.9,3.2]
}
frame = pd.DataFrame(data)

In [28]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada   200  2.9
5  Nevada  2003  3.2

In [29]:
## select only firest fine rows: 
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada   200  2.9

In [30]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt']
                      ,index=['one','two','three','four','five','six'])

In [31]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five    200  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [33]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [34]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five      200
six      2003
Name: year, dtype: int64

In [38]:
frame2.state
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five    200  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [37]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [39]:
## assignment debt
frame2['debt'] = 16.5

In [40]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five    200  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [43]:
frame2['debt'] = np.arange(6.) 
#“length must match the length of the DataFrame”


In [42]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five    200  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

**Series**, nhãn của chuỗi sẽ được thiết kế lại chính xác với chỉ mục của DataFrame, chèn các giá trị bị thiếu vào bất kỳ lỗ nào:”

In [45]:
val = pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])
frame2['debt'] = val

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five    200  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

“Assigning a column that doesn’t exist will create a new column. The del keyword will delete columns as with a dict” 

In [47]:
frame2['eastern'] = frame2.state == 'Ohio'

In [48]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five    200  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

**New columns cannot be created with the frame2.eastern syntax**



## Delete Columns

In [49]:
del frame2['eastern']

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
pop = {
    'Nevada': {
        2001:2.4,
        2002:2.9
    },
    'Ohio': {
        2000:1.5,
        2001: 1.7,
        2002:3.6
    }
}


In [52]:
frame3 = pd.DataFrame(pop)

In [53]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

# Chuyển vị Data Frame

In [54]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [55]:
frame3.index.name= 'year'
frame3.columns.name = 'state'

In [57]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [59]:
frame3.values ## return two-dimentional

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [60]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [200, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [61]:
obj = pd.Series(range(3),index=['a','b','c'])
index = obj.index

In [62]:
index

Index(['a', 'b', 'c'], dtype='object')

**Index objects are immutable and thus can’t be modified by the user:**


In [63]:
labels = pd.Index(np.arange(3))

In [64]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [65]:
obj2 = pd.Series([1.5,-2.5,0],index=labels)

In [66]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [67]:
obj2.index is labels

True

**“Unlike Python sets, a pandas Index can contain duplicate labels:”**



In [68]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

##  Essential Functionality

## 1.1 Reindexing

Một phương pháp quan trọng trên các đối tượng pandas là `reindex`, có nghĩa là tạo một đối tượng mới với dữ liệu phù hợp với một `index`  mới. Hãy xem xét một ví dụ:

In [69]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [70]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [71]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])

In [72]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [73]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [75]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                         index=['a', 'c', 'd'],
                         columns=['Ohio', 'Texas','California'])
frame


Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [76]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [84]:
states = ['Texas','California']
states

['Texas', 'California']

In [85]:
frame.reindex(columns = states)

Texas  California
a      1           2
c      4           5
d      7           8

In [87]:
frame.loc[['a', 'c', 'd'], states]

Texas  California
a      1           2
c      4           5
d      7           8

## Dropping Entries from an Axis

In [89]:
obj = pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [90]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [91]:
new_obj = obj.drop('c')

In [92]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [93]:
obj.drop(['b','c'])

a    0.0
d    3.0
e    4.0
dtype: float64

## “Indexing, Selection, and Filtering” 

In [94]:
obj = pd.Series(np.arange(4.),index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [95]:
obj['b']

1.0

In [96]:
obj[1]

1.0

In [97]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [98]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [99]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [100]:
## Slicing 
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [101]:
# Setting
obj['b':'c']= 5

In [102]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [103]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])

In [104]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [106]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [107]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

## Selection with Loc and iLoc

In [108]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

dể lập `index` nhãn DataFrame trên các hàng, tôi giới thiệu các toán tử lập chỉ mục đặc biệt **loc** và **iloc**. Chúng cho phép bạn chọn một tập hợp con của các hàng và cột từ DataFrame với ký hiệu giống NumPy bằng cách sử dụng nhãn trục (loc) hoặc số nguyên (iloc) ”.

In [112]:
data.loc['Colorado',['two','three']]
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [111]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [113]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

## Integer Indexes 
Làm việc với các đối tượng **pandas** được lập chỉ mục bởi các số nguyên là thứ thường thu hút người dùng mới do một số khác biệt với ngữ nghĩa lập chỉ mục trên các cấu trúc dữ liệu Python tích hợp sẵn như danh sách và bộ dữ liệu. Ví dụ: bạn có thể không mong đợi đoạn mã sau tạo ra lỗi: ”

In [114]:
ser = pd.Series(np.arange(3.))
ser



0    0.0
1    1.0
2    2.0
dtype: float64

On the other hand, with a non-integer index, there is no potential for ambiguity


In [117]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

2.0

## “Arithmetic and Data Alignment”


Một tính năng quan trọng của **pandas** đối với một số ứng dụng là hành vi số học giữa các đối tượng có chỉ số khác nhau. Khi bạn đang thêm các đối tượng cùng nhau, nếu bất kỳ cặp chỉ mục nào không giống nhau, chỉ mục tương ứng trong kết quả sẽ là hợp nhất của các cặp **index**. Đối với người dùng có kinh nghiệm cơ sở dữ liệu, điều này tương tự như một phép nối ngoài tự động trên các nhãn chỉ mục. Hãy xem một ví dụ:

In [119]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [120]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [121]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [122]:
s1 + s2 

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

Việc căn chỉnh dữ liệu nội bộ giới thiệu các giá trị còn thiếu ở các vị trí nhãn không trùng lặp. Các giá trị bị thiếu sau đó sẽ lan truyền trong các phép tính số học tiếp theo.

Trong trường hợp của DataFrame, căn chỉnh được thực hiện trên cả hàng và cột:

In [125]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns=list('bcd'),
                  index = ['Ohio','Texas','Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index =['Utah','Ohio','Texas','Oregon'])

In [126]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [127]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [128]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

## Arithmetic methods with fill values”
Trong các phép toán số học giữa các đối tượng được lập chỉ mục khác nhau, bạn có thể muốn điền vào một giá trị đặc biệt, chẳng hạn như 0, khi nhãn trục được tìm thấy trong một đối tượng chứ không phải đối tượng khác:


In [129]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                  columns = list('abcde'))

In [130]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [131]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [133]:
df2.loc[1,'b'] = np.nan

In [134]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [135]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [136]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [137]:
df1.add(df2,fill_value=0) ## file value NAN = 0

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

“Relatedly, when reindexing a Series or DataFrame, you can also specify a different fill value”


In [141]:
df1.reindex(columns = df2.columns,fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## Operations between DataFrame and Series
Như với mảng NumPy có các kích thước khác nhau, số học giữa DataFrame và Series cũng được xác định. Trước tiên, để làm ví dụ thúc đẩy, hãy xem xét sự khác biệt giữa mảng hai chiều và một trong các hàng của nó ”

In [145]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [146]:
arr[0]

array([0., 1., 2., 3.])

In [147]:
arr - arr[0] ## Mutile each rows

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [148]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns = list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])

In [149]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [150]:
series = frame.iloc[0]

In [151]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [152]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

## Function Applicaiotn and Mapping 

In [153]:
frame  = pd.DataFrame(np.random.randn(4,3),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])

In [154]:
frame

b         d         e
Utah    1.361127  0.329511  0.746983
Ohio   -0.527813 -0.299911  0.376300
Texas  -1.374385  0.189120  1.239384
Oregon -1.448566 -0.617478 -1.775218

In [155]:
np.abs(frame)

b         d         e
Utah    1.361127  0.329511  0.746983
Ohio    0.527813  0.299911  0.376300
Texas   1.374385  0.189120  1.239384
Oregon  1.448566  0.617478  1.775218

In [157]:
frame

b         d         e
Utah    1.361127  0.329511  0.746983
Ohio   -0.527813 -0.299911  0.376300
Texas  -1.374385  0.189120  1.239384
Oregon -1.448566 -0.617478 -1.775218

In [156]:
f = lambda x : x.max() - x.min()
frame.apply(f)

b    2.809692
d    0.946989
e    3.014602
dtype: float64

In [159]:
frame.apply(f,axis =1)

Utah      1.031615
Ohio      0.904113
Texas     2.613769
Oregon    1.157740
dtype: float64

In [160]:
format = lambda x : '%.2f' % x
frame.applymap(format)

b      d      e
Utah     1.36   0.33   0.75
Ohio    -0.53  -0.30   0.38
Texas   -1.37   0.19   1.24
Oregon  -1.45  -0.62  -1.78

## Sorting and Ranking 
Sắp xếp tập dữ liệu theo một số tiêu chí là một hoạt động quan trọng khác được tích hợp sẵn. Để sắp xếp từ vựng theo chỉ mục hàng hoặc cột, hãy sử dụng phương thức sort_index, phương thức này trả về một đối tượng mới, được sắp xếp ”

In [161]:
obj = pd.Series(range(4),index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

#“With a DataFrame, you can sort by index on either axis:




In [163]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns = ['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [164]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [165]:
#“The data is sorted in ascending order by default,
#but can be sorted in descending order, too:”

frame.sort_index(axis = 1, ascending= False)


d  c  b  a
three  0  3  2  1
one    4  7  6  5

###### Sort by values

In [166]:
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [167]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

## 5.3 Tổng và tính toán thống kê mô tả

Các đối tượng **panda** được trang bị một tập hợp các phương pháp thống kê và toán học phổ biến. Hầu hết các phương pháp này thuộc loại giảm thiểu hoặc thống kê tóm tắt, các phương pháp trích xuất một giá trị (như tổng hoặc giá trị trung bình) từ Chuỗi hoặc Chuỗi giá trị từ các hàng hoặc cột của DataFrame. So với các phương pháp tương tự được tìm thấy trên mảng NumPy, chúng có khả năng xử lý tích hợp đối với dữ liệu bị thiếu. Hãy xem xét một DataFrame nhỏ:

In [169]:
df = pd.DataFrame([
    [1.4,np.nan],
    [7.1,-4.5],
    [np.nan,np.nan],
    [0.75,-1.3]
],
 index=['a','b','c','d'],
    columns = ['one','two']
)

In [170]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [171]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [172]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64